language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
env:
  - BUILD_TYPE=Debug 
  - BUILD_TYPE=Release STATIC=On
script:
  - mkdir out
  - cd out
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build . -- -j2
  - ctest --output-on-failure -D ExperimentalBuild -j2
  - ctest --output-on-failure -D ExperimentalTest -j2
